CREATE TABLE CAT_TIENDAS(
    ID_TIENDA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOMBRE_TIENDA VARCHAR(30),
    DESCRIPCION_TIENDA TEXT,
    PRIMARY KEY (ID_TIENDA),    
);

CREATE table CAT_ARTICULOS_VENTA(
	ID_ARTICULO_ARTICULO_VENTA INT not null unique auto_increment,
	NOMBRE_ARTICULO VARCHAR(30),
	ID_TIPO_ARTICULO INT,
	DESCRIPCION_ARTICULO TEXT,
	PRECIO_ARTICULO DECIMAL(10,2),
	ID_TIENDA INT,
	primary KEY(ID_ARTICULO),
	FOREIGN KEY (ID_TIPO_ARTICULO) REFERENCES CAT_TIPO_ARTICULO(ID_TIPO_ARTICULO),
	FOREIGN KEY (ID_TIENDA) REFERENCES CAT_TIENDAS(ID_TIENDA)
);

create table  CAT_INSUMOS(
	ID_INSUMO INT not null unique auto_increment,
	NOMBRE_INSUMO VARCHAR(30),
	DESCRIPCION_INSUMO,
	primary KEY(ID_INSUMO)
);

create table CAT_TIPO_ARTICULO(
	ID_TIPO_ARTICULO INT not null unique auto_increment,
	CATEGORIA_ARTICULO VARCHAR(35),
	DESCRIPICON_CATEGORIA TEXT,
	primary KEY(ID_TIPO_ARTICULO)	
);

create table INVENTARIO_ARTICULOS_VENTA(
	ID_ID_ARTICULO_ARTICULO_VENTA INT not null unique auto_increment,
	ID_TIENDA INT,
	CANTIDAD INT,
	FECHA_ENTRADA DATE,
	FECHA_ACTUALIZACION DATE,
	FOREIGN KEY (ID_TIENDA) REFERENCES CAT_TIENDAS(ID_TIENDA),
	FOREIGN KEY (ID_ID_ARTICULO_ARTICULO_VENTA) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_ARTICULO_VENTA)
);