CREATE TABLE CAT_TIENDAS(
    ID_TIENDA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOMBRE_TIENDA VARCHAR(30),
    DESCRIPCION_TIENDA TEXT,
    PRIMARY KEY (ID_TIENDA),    
);

CREATE table CAT_ARTICULOS_VENTA(
	ID_ARTICULO_VENTA INT not null unique auto_increment,
	NOMBRE_ARTICULO VARCHAR(30),
	ID_TIPO_ARTICULO INT,
	DESCRIPCION_ARTICULO TEXT,
	PRECIO_ARTICULO DECIMAL(10,2),	
	primary KEY(ID_ARTICULO_VENTA),
	FOREIGN KEY (ID_TIPO_ARTICULO) REFERENCES CAT_TIPO_ARTICULO(ID_TIPO_ARTICULO)	
);

create table CAT_TIPO_ARTICULO(
	ID_TIPO_ARTICULO INT not null unique auto_increment,
	CATEGORIA_ARTICULO VARCHAR(35),
	DESCRIPICON_CATEGORIA TEXT,
	primary KEY(ID_TIPO_ARTICULO)	
);

CREATE TABLE CAT_TIPO_PAGO(
	ID_TIPO_PAGO INT NOT NULL UNIQUE AUTO_INCREMENT,
	TIPO_PAGO VARCHAR(25),
	DESCRIPCION_PAGO TEXT,
	PRIMARY KEY(ID_TIPO_PAGO)
);

CREATE TABLE DETALLE_TICKET(
	ID_DETALLE_TICKET INT NOT NULL UNIQUE AUTO_INCREMENT,
	ID_ARTICULO_VENTA INT,
	ID_TICKET INT,
	CANTIDAD_ARTICULOS INT,	
	TOTAL_VENTA DECIMAL(10,2),
	PRIMARY KEY (ID_DETALLE_TICKET),
	FOREIGN KEY (ID_ARTICULO_VENTA) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_VENTA),
	FOREIGN KEY (ID_TICKET) REFERENCES TICKET_VENTA(ID_TICKET)	
);

CREATE TABLE TICKET_VENTA(
	ID_TICKET INT NOT NULL UNIQUE AUTO_INCREMENT,
	FOLIO_TICKET VARCHAR(15),
	FECHA_TICKET DATETIME DEFAULT CURRENT_TIMESTAMP,
	USUARIO_INFO_ID INT,
	ID_TIPO_PAGO INT,
	SUBTOTAL DECIMAL(10,2),
	TOTAL DECIMAL(10,2),
	IMPUESTOS DECIMAL(10,2),
	OBSERVACIONES TEXT,
	ACTIVO BOOLEAN,
	PRIMARY KEY (ID_TICKET),
	FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
	FOREIGN KEY (ID_TIPO_PAGO) REFERENCES CAT_TIPO_PAGO(ID_TIPO_PAGO)		
);


create table  CAT_INSUMOS(
	ID_INSUMO INT not null unique auto_increment,
	NOMBRE_INSUMO VARCHAR(30),
	DESCRIPCION_INSUMO,
	primary KEY(ID_INSUMO)
);
create table INVENTARIO_ARTICULOS_VENTA(
	ID_ID_ARTICULO_ARTICULO_VENTA INT not null unique auto_increment,
	ID_TIENDA INT,
	CANTIDAD INT,
	FECHA_ENTRADA DATE,
	FECHA_ACTUALIZACION DATE,
	FOREIGN KEY (ID_TIENDA) REFERENCES CAT_TIENDAS(ID_TIENDA),
	FOREIGN KEY (ID_ID_ARTICULO_ARTICULO_VENTA) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_ARTICULO_VENTA)
);