DROP DATABASE MI_CAFETERIA;

CREATE DATABASE MI_CAFETERIA;

USE MI_CAFETERIA;

CREATE TABLE USUARIOS_INFO(
    USUARIO_INFO_ID INT NOT NULL UNIQUE AUTO_INCREMENT,    
    NOMBRE_USUARIO VARCHAR(30),
    APELLIDO_PATERNO_USUARIO VARCHAR(30),
    APELLIDO_MATERNO_USUARIO VARCHAR(30),
    EMAIL VARCHAR(100),
    PRIMARY KEY(USUARIO_INFO_ID)
);
    
    
CREATE TABLE USUARIOS_PWD (
    USUARIO_PWD_ID INT NOT NULL UNIQUE AUTO_INCREMENT, 
    USUARIO_INFO_ID INT,   
    NICKNAME VARCHAR(10),
    PWRD VARCHAR(20),
    PRIMARY KEY(USUARIO_PWD_ID),
    FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID)
);

CREATE TABLE LOGIN(
    LOGIN_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USUARIO_PWD_ID INT,
    TOKEN TEXT,
    PRIMARY KEY(LOGIN_ID),
    FOREIGN KEY (USUARIO_PWD_ID) REFERENCES USUARIOS_PWD(USUARIO_PWD_ID)
);
