DROP DATABASE IF EXISTS MI_CAFETERIA;

CREATE DATABASE MI_CAFETERIA;

-- Connect to the database using: \c MI_CAFETERIA

CREATE TABLE USUARIOS_INFO(
    USUARIO_INFO_ID SERIAL NOT NULL UNIQUE,
    NOMBRE_USUARIO VARCHAR(30),
    APELLIDO_PATERNO_USUARIO VARCHAR(30),
    APELLIDO_MATERNO_USUARIO VARCHAR(30),
    EMAIL VARCHAR(100),
    PRIMARY KEY(USUARIO_INFO_ID)
);
    
    
CREATE TABLE USUARIOS_PWD (
    USUARIO_PWD_ID SERIAL NOT NULL UNIQUE,
    USUARIO_INFO_ID INT,
    NICKNAME VARCHAR(15),
    PWRD VARCHAR(255),
    PRIMARY KEY(USUARIO_PWD_ID),
    FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID)
);

CREATE TABLE LOGIN(
    LOGIN_ID SERIAL NOT NULL UNIQUE,
    USUARIO_PWD_ID INT,
    TOKEN TEXT,
    PRIMARY KEY(LOGIN_ID),
    FOREIGN KEY (USUARIO_PWD_ID) REFERENCES USUARIOS_PWD(USUARIO_PWD_ID)
);

ALTER TABLE LOGIN
ADD COLUMN FECHA_LOGIN DATE DEFAULT CURRENT_DATE;
