CREATE TABLE ROLES(
    ROL_ID INT NOT NULL UNIQUE AUTO_INCREMENT,    
    NOMBRE_ROL VARCHAR(10),
    DESCRIPCION_ROL TEXT,    
    PRIMARY KEY(ROL_ID)
);

CREATE TABLE ROLES_USUARIOS(
    USUARIO_ID INT,
    ROL_ID INT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID)
);