DROP database if exists MI_CAFETERIA;

CREATE DATABASE MI_CAFETERIA;

USE MI_CAFETERIA;

CREATE TABLE USUARIOS_INFO(
    USUARIO_INFO_ID INT NOT NULL UNIQUE AUTO_INCREMENT,    
    NOMBRE_USUARIO VARCHAR(30),
    APELLIDO_PATERNO_USUARIO VARCHAR(30),
    APELLIDO_MATERNO_USUARIO VARCHAR(30),
    EMAIL VARCHAR(100),
    PRIMARY KEY(USUARIO_INFO_ID)
);
    
    
CREATE TABLE USUARIOS_PWD (
    USUARIO_PWD_ID INT NOT NULL UNIQUE AUTO_INCREMENT, 
    USUARIO_INFO_ID INT,   
    NICKNAME VARCHAR(15),
    PWRD VARCHAR(255),
    PRIMARY KEY(USUARIO_PWD_ID),
    FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID)
);

CREATE TABLE LOGIN(
    LOGIN_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USUARIO_PWD_ID INT,
    TOKEN TEXT,
    PRIMARY KEY(LOGIN_ID),
    FOREIGN KEY (USUARIO_PWD_ID) REFERENCES USUARIOS_PWD(USUARIO_PWD_ID)
);

alter table login 
add FECHA_LOGIN DATE default CURRENT_DATE();

CREATE TABLE ROLES(
    ROL_ID INT NOT NULL UNIQUE AUTO_INCREMENT,    
    NOMBRE_ROL VARCHAR(10),
    DESCRIPCION_ROL TEXT,    
    PRIMARY KEY(ROL_ID)
);

CREATE TABLE ROLES_USUARIOS(
    USUARIO_ID INT,
    ROL_ID INT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID)
);
create table CAT_TIPO_ARTICULO(
	ID_TIPO_ARTICULO INT not null unique auto_increment,
	CATEGORIA_ARTICULO VARCHAR(35),
	DESCRIPICON_CATEGORIA TEXT,
	primary KEY(ID_TIPO_ARTICULO)	
);

CREATE table CAT_ARTICULOS_VENTA(
	ID_ARTICULO_VENTA INT not null unique auto_increment,
	NOMBRE_ARTICULO VARCHAR(30),
	ID_TIPO_ARTICULO INT,
	DESCRIPCION_ARTICULO TEXT,
	PRECIO_ARTICULO DECIMAL(10,2),	
	primary KEY(ID_ARTICULO_VENTA),
	FOREIGN KEY (ID_TIPO_ARTICULO) REFERENCES CAT_TIPO_ARTICULO(ID_TIPO_ARTICULO)	
);



CREATE TABLE CAT_TIPO_PAGO(
	ID_TIPO_PAGO INT NOT NULL UNIQUE AUTO_INCREMENT,
	TIPO_PAGO VARCHAR(25),
	DESCRIPCION_PAGO TEXT,
	PRIMARY KEY(ID_TIPO_PAGO)
);
CREATE TABLE TICKET_VENTA(
	ID_TICKET INT NOT NULL UNIQUE AUTO_INCREMENT,
	FOLIO_TICKET VARCHAR(15),
	FECHA_TICKET DATETIME DEFAULT CURRENT_TIMESTAMP,
	USUARIO_INFO_ID INT,
	ID_TIPO_PAGO INT,
	SUBTOTAL DECIMAL(10,2),
	TOTAL DECIMAL(10,2),
	IMPUESTOS DECIMAL(10,2),
	OBSERVACIONES TEXT,
	ACTIVO BOOLEAN,
	PRIMARY KEY (ID_TICKET),
	FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
	FOREIGN KEY (ID_TIPO_PAGO) REFERENCES CAT_TIPO_PAGO(ID_TIPO_PAGO)		
);
CREATE TABLE DETALLE_TICKET(
	ID_DETALLE_TICKET INT NOT NULL UNIQUE AUTO_INCREMENT,
	ID_ARTICULO_VENTA INT,
	ID_TICKET INT,
	CANTIDAD_ARTICULOS INT,	
	TOTAL_VENTA DECIMAL(10,2),
	PRIMARY KEY (ID_DETALLE_TICKET),
	FOREIGN KEY (ID_ARTICULO_VENTA) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_VENTA),
	FOREIGN KEY (ID_TICKET) REFERENCES TICKET_VENTA(ID_TICKET)	
);


create table CAT_EXTRAS(
	ID_EXTRA INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_EXTRA VARCHAR(25),
	DESCRIPCION_EXTRA TEXT,
	PRECIO_EXTRA DECIMAL(10,2)

);
CREATE TABLE DESCUENTO_ARTICULO(
	ID_DESCUENTO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_DESCUENTO VARCHAR(25),
	DESCRIPCION_DESCUENTO TEXT,
	DESCUENTO_PORCENTAJE DECIMAL(5,2)
);

CREATE TABLE DETALLE_TICKET_EXTRAS (
    ID_DETALLE_TICKET INT NOT NULL,
    ID_EXTRA INT NOT NULL,
    PRIMARY KEY (ID_DETALLE_TICKET, ID_EXTRA),
    FOREIGN KEY (ID_DETALLE_TICKET) REFERENCES DETALLE_TICKET(ID_DETALLE_TICKET),
    FOREIGN KEY (ID_EXTRA) REFERENCES CAT_EXTRAS(ID_EXTRA)
);

ALTER TABLE DETALLE_TICKET
ADD COLUMN ID_DESCUENTO INT,
ADD COLUMN ID_EXTRA INT;

ALTER table DETALLE_TICKET
ADD CONSTRAINT fk_descuento
FOREIGN KEY (ID_DESCUENTO) REFERENCES DESCUENTO_ARTICULO(ID_DESCUENTO);

ALTER table DETALLE_TICKET
ADD CONSTRAINT fk_extra
FOREIGN KEY (ID_EXTRA) REFERENCES CAT_EXTRAS(ID_EXTRA);


CREATE TABLE PAQUETE(
	ID_PAQUETE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_PAQUETE VARCHAR(100),
	DESCRIPCION TEXT,
	PRECIO_PAQUETE DECIMAL(10,2)NOT NULL	
);

CREATE TABLE DETALLE_PAQUETE(
	ID_DETALLE_PAQUETE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_PAQUETE INT NOT NULL,
	ID_ARTICULO INT NOT NULL,
	CANTIDAD INT NOT NULL DEFAULT 1,
	FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID_PAQUETE),
	FOREIGN KEY (ID_ARTICULO) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_VENTA)
);

ALTER TABLE DETALLE_TICKET
ADD COLUMN ID_PAQUETE INT;

ALTER table DETALLE_TICKET
ADD CONSTRAINT fk_paquete
FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID_PAQUETE);

insert into roles (NOMBRE_ROL,DESCRIPCION_ROL)
values('SUPER USER','ROL SUPER USUARIO, PARA VER CONFIGURACIONES Y PRUEBAS DEL SISTEMA');