DROP DATABASE IF EXISTS MI_CAFETERIA;

CREATE DATABASE MI_CAFETERIA;

-- Connect to the database (in psql: \c MI_CAFETERIA;)

CREATE TABLE USUARIOS_INFO(
    USUARIO_INFO_ID SERIAL NOT NULL UNIQUE,
    NOMBRE_USUARIO VARCHAR(30),
    APELLIDO_PATERNO_USUARIO VARCHAR(30),
    APELLIDO_MATERNO_USUARIO VARCHAR(30),
    EMAIL VARCHAR(100),
    PRIMARY KEY(USUARIO_INFO_ID)
);


CREATE TABLE USUARIOS_PWD (
    USUARIO_PWD_ID SERIAL NOT NULL UNIQUE,
    USUARIO_INFO_ID INT,
    NICKNAME VARCHAR(15),
    PWRD VARCHAR(255),
    PRIMARY KEY(USUARIO_PWD_ID),
    FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID)
);

CREATE TABLE LOGIN(
    LOGIN_ID SERIAL NOT NULL UNIQUE,
    USUARIO_PWD_ID INT,
    TOKEN TEXT,
    PRIMARY KEY(LOGIN_ID),
    FOREIGN KEY (USUARIO_PWD_ID) REFERENCES USUARIOS_PWD(USUARIO_PWD_ID)
);

ALTER TABLE LOGIN
ADD COLUMN FECHA_LOGIN DATE DEFAULT CURRENT_DATE;

CREATE TABLE ROLES(
    ROL_ID SERIAL NOT NULL UNIQUE,
    NOMBRE_ROL VARCHAR(10),
    DESCRIPCION_ROL TEXT,
    PRIMARY KEY(ROL_ID)
);

CREATE TABLE ROLES_USUARIOS(
    USUARIO_ID INT,
    ROL_ID INT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID)
);

CREATE TABLE CAT_TIPO_ARTICULO(
    ID_TIPO_ARTICULO SERIAL NOT NULL UNIQUE,
    CATEGORIA_ARTICULO VARCHAR(35),
    DESCRIPICON_CATEGORIA TEXT,
    PRIMARY KEY(ID_TIPO_ARTICULO)
);

CREATE TABLE CAT_ARTICULOS_VENTA(
    ID_ARTICULO_VENTA SERIAL NOT NULL UNIQUE,
    NOMBRE_ARTICULO VARCHAR(30),
    ID_TIPO_ARTICULO INT,
    DESCRIPCION_ARTICULO TEXT,
    PRECIO_ARTICULO DECIMAL(10,2),
    PRIMARY KEY(ID_ARTICULO_VENTA),
    FOREIGN KEY (ID_TIPO_ARTICULO) REFERENCES CAT_TIPO_ARTICULO(ID_TIPO_ARTICULO)
);

CREATE TABLE CAT_TIPO_PAGO(
    ID_TIPO_PAGO SERIAL NOT NULL UNIQUE,
    TIPO_PAGO VARCHAR(25),
    DESCRIPCION_PAGO TEXT,
    PRIMARY KEY(ID_TIPO_PAGO)
);

CREATE TABLE TICKET_VENTA(
    ID_TICKET SERIAL NOT NULL UNIQUE,
    FOLIO_TICKET VARCHAR(15),
    FECHA_TICKET TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_INFO_ID INT,
    ID_TIPO_PAGO INT,
    SUBTOTAL DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    IMPUESTOS DECIMAL(10,2),
    OBSERVACIONES TEXT,
    ACTIVO BOOLEAN,
    PRIMARY KEY (ID_TICKET),
    FOREIGN KEY (USUARIO_INFO_ID) REFERENCES USUARIOS_INFO(USUARIO_INFO_ID),
    FOREIGN KEY (ID_TIPO_PAGO) REFERENCES CAT_TIPO_PAGO(ID_TIPO_PAGO)
);

CREATE TABLE DETALLE_TICKET(
    ID_DETALLE_TICKET SERIAL NOT NULL UNIQUE,
    ID_ARTICULO_VENTA INT,
    ID_TICKET INT,
    CANTIDAD_ARTICULOS INT,
    TOTAL_VENTA DECIMAL(10,2),
    PRIMARY KEY (ID_DETALLE_TICKET),
    FOREIGN KEY (ID_ARTICULO_VENTA) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_VENTA),
    FOREIGN KEY (ID_TICKET) REFERENCES TICKET_VENTA(ID_TICKET)
);

CREATE TABLE CAT_EXTRAS(
    ID_EXTRA SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NOMBRE_EXTRA VARCHAR(25),
    DESCRIPCION_EXTRA TEXT,
    PRECIO_EXTRA DECIMAL(10,2)
);

CREATE TABLE DESCUENTO_ARTICULO(
    ID_DESCUENTO SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NOMBRE_DESCUENTO VARCHAR(25),
    DESCRIPCION_DESCUENTO TEXT,
    DESCUENTO_PORCENTAJE DECIMAL(5,2)
);

CREATE TABLE DETALLE_TICKET_EXTRAS (
    ID_DETALLE_TICKET INT NOT NULL,
    ID_EXTRA INT NOT NULL,
    PRIMARY KEY (ID_DETALLE_TICKET, ID_EXTRA),
    FOREIGN KEY (ID_DETALLE_TICKET) REFERENCES DETALLE_TICKET(ID_DETALLE_TICKET),
    FOREIGN KEY (ID_EXTRA) REFERENCES CAT_EXTRAS(ID_EXTRA)
);

ALTER TABLE DETALLE_TICKET
ADD COLUMN ID_DESCUENTO INT,
ADD COLUMN ID_EXTRA INT;

ALTER TABLE DETALLE_TICKET
ADD CONSTRAINT fk_descuento
FOREIGN KEY (ID_DESCUENTO) REFERENCES DESCUENTO_ARTICULO(ID_DESCUENTO);

ALTER TABLE DETALLE_TICKET
ADD CONSTRAINT fk_extra
FOREIGN KEY (ID_EXTRA) REFERENCES CAT_EXTRAS(ID_EXTRA);

CREATE TABLE PAQUETE(
    ID_PAQUETE SERIAL NOT NULL PRIMARY KEY,
    NOMBRE_PAQUETE VARCHAR(100),
    DESCRIPCION TEXT,
    PRECIO_PAQUETE DECIMAL(10,2) NOT NULL
);

CREATE TABLE DETALLE_PAQUETE(
    ID_DETALLE_PAQUETE SERIAL NOT NULL PRIMARY KEY,
    ID_PAQUETE INT NOT NULL,
    ID_ARTICULO INT NOT NULL,
    CANTIDAD INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID_PAQUETE),
    FOREIGN KEY (ID_ARTICULO) REFERENCES CAT_ARTICULOS_VENTA(ID_ARTICULO_VENTA)
);

ALTER TABLE DETALLE_TICKET
ADD COLUMN ID_PAQUETE INT;

ALTER TABLE DETALLE_TICKET
ADD CONSTRAINT fk_paquete
FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID_PAQUETE);

INSERT INTO ROLES (NOMBRE_ROL, DESCRIPCION_ROL)
VALUES ('SUPER USER', 'ROL SUPER USUARIO, PARA VER CONFIGURACIONES Y PRUEBAS DEL SISTEMA');